### PR TITLE
Bump onno-vos-dev submodule

### PR DESCRIPTION
**Pull request by onno-vos-dev**
This bumps my submodule to the new `main` which includes the following changes:
* Use binary matching all the way
* Use fn32v hashing for hashing the cities along the way rather than matching out the cities
* Improve spawn options for workers

Results on my Mac M1 Pro compared to the fastest previous solution from Jesperes. a 17.2% improvement on the 1B results. For some reason its a slower on the 50M results. Something that I'm looking into tonight 👍 

50M results:
| Contributor | Time (50M) | CPU% (50M) | Mem kb (50M) |
| ----------- | ---------- | ---------- | ------------ |
| jesperes    |    0:01.00 |       533% |       141216 |
| onno-vos-dev|    0:01.61 |       247% |       549280 |

1B results:
| Contributor | Time (1B) | CPU% (1B) | Mem kb (1B) |
| ----------- | ---------- | ---------- | ------------ |
| onno-vos-dev|    0:09.44 |       793% |       623056 |
| jesperes    |    0:11.40 |       880% |       145216 |

### CODE REVIEW

**Comment by IceDragon200** [comment]
Oooh, let's see how well it does on the ryzen then

**Comment by IceDragon200** [comment]
Bad news crashed it:
```
Runtime terminating during boot ({function_clause,[{brc,match_cities,[[],[<<"Pittsburgh">>,<<"Dili">>,<<"Hargeisa">>,<<"Batumi">>,<<"Havana">>,<<"Saskatoon">>,<<"Toluca">>,<<"Da Lat">>,<<"Philadelphia">>,<<"Gjoa Haven">>,<<"Hat Yai">>,<<"Tamanrasset">>,<<"Yellowknife">>,<<"Asmara">>,<<"Halifax">>,<<"Addis Ababa">>,<<"Accra">>,<<"Harare">>,<<"Hargeisa">>,<<"La Paz">>,<<87,114,111,99,197,130,97,119>>,<<"Guadalajara">>,<<"Shanghai">>,<<"Gaborone">>,<<"Montreal">>,<<"Porto">>,<<"Skopje">>,<<"Nouakchott">>,<<"Tucson">>,<<"Mexico City">>,<<"Valletta">>,<<"Astana">>,<<"Wellington">>,<<"Singapore">>,<<"Nicosia">>,<<"Bratislava">>,<<"Tucson">>,<<"Zanzibar City">>,<<"Burnie">>,<<"Seattle">>,<<"Kabul">>,<<"Brisbane">>,<<"San Juan">>,<<"Irkutsk">>,<<"Djibouti">>,<<"Sokoto">>,<<"Petropavlovsk-Kamchatsky">>,<<"Hamilton">>,<<"Monterrey">>,<<"Antananarivo">>,<<"Mumbai">>,<<"Suva">>,<<"Kathmandu">>,<<"Lake Havasu City">>,<<"Alexandria">>,<<"Bangui">>,<<"Cabo San Lucas">>,<<"Melbourne">>,<<"Palmerston North">>,<<"Pretoria">>,
```

That's all I got from the log

**Comment by onno-vos-dev** [comment]
> Bad news crashed it:
> 
> ```
> Runtime terminating during boot ({function_clause,[{brc,match_cities,[[],[<<"Pittsburgh">>,<<"Dili">>,<<"Hargeisa">>,<<"Batumi">>,<<"Havana">>,<<"Saskatoon">>,<<"Toluca">>,<<"Da Lat">>,<<"Philadelphia">>,<<"Gjoa Haven">>,<<"Hat Yai">>,<<"Tamanrasset">>,<<"Yellowknife">>,<<"Asmara">>,<<"Halifax">>,<<"Addis Ababa">>,<<"Accra">>,<<"Harare">>,<<"Hargeisa">>,<<"La Paz">>,<<87,114,111,99,197,130,97,119>>,<<"Guadalajara">>,<<"Shanghai">>,<<"Gaborone">>,<<"Montreal">>,<<"Porto">>,<<"Skopje">>,<<"Nouakchott">>,<<"Tucson">>,<<"Mexico City">>,<<"Valletta">>,<<"Astana">>,<<"Wellington">>,<<"Singapore">>,<<"Nicosia">>,<<"Bratislava">>,<<"Tucson">>,<<"Zanzibar City">>,<<"Burnie">>,<<"Seattle">>,<<"Kabul">>,<<"Brisbane">>,<<"San Juan">>,<<"Irkutsk">>,<<"Djibouti">>,<<"Sokoto">>,<<"Petropavlovsk-Kamchatsky">>,<<"Hamilton">>,<<"Monterrey">>,<<"Antananarivo">>,<<"Mumbai">>,<<"Suva">>,<<"Kathmandu">>,<<"Lake Havasu City">>,<<"Alexandria">>,<<"Bangui">>,<<"Cabo San Lucas">>,<<"Melbourne">>,<<"Palmerston North">>,<<"Pretoria">>,
> ```
> 
> That's all I got from the log

I know the problem 👍 Will push a fix.

**Comment by onno-vos-dev** [comment]
See: https://github.com/IceDragon200/1brc_erl_ex_test/pull/6

**Pull request merged**
